filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            not:
              or:
                - contains:
                    container.image: "elasticsearch"
                - contains:
                    container.image: "kibana"
                - contains:
                    container.image: "logstash"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.to_stderr: true
logging.level: info