input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "service" => "%{[container][name]}"
      "instance" => "%{[container][id]}"
    }
  }

  if [message] =~ /^\{.*/ {
    json {
      source => "message"
      target => "parsed"
      tag_on_failure => ["json_parse_failed"]
    }

    if ![parsed][message] {
      mutate {
        add_field => { "[parsed][message]" => "%{message}" }
      }
    }

    mutate {
      rename => {
        "[parsed][app_name]" => "app_name"
        "[parsed][instance_id]" => "instance_id"
        "[parsed][traceId]" => "traceId"
        "[parsed][spanId]" => "spanId"
        "[parsed][level]" => "level"
        "[parsed][logger_name]" => "logger"
        "[parsed][message]" => "message"
        "[parsed][stack_trace]" => "stack_trace"
      }
      remove_field => ["parsed"]
    }
  } else {
    mutate {
      add_field => {
        "level" => "INFO"
      }
    }
  }

  if ![traceId] {
    mutate { add_field => { "traceId" => "n/a" } }
  }

  if ![spanId] {
    mutate { add_field => { "spanId" => "n/a" } }
  }

  mutate {
    remove_field => ["@version", "agent", "ecs", "input", "log", "tags"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "autonotes-logs-%{+YYYY.MM.dd}"
  }
}
