input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /^\{.*/ {
    json {
      source => "message"
    }
  }

  mutate {
    remove_field => ["@version", "agent", "ecs", "input", "log", "tags"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "autonotes-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}